# Site settings
title: Spring By Examples Blog
header-img: img/home-bg.jpg
email: preemynence@gmail.com
description: "This is our place where we share the expertise and knowledge we acquired."
baseurl: ""
url: "https://github.com/preemynence/SpringProjectSamples"
twitter_username: preemynence
github_username:  preemynence
# facebook_username:  IronSummitMedia

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]